### ISSUE TITLE
Weights for backbone (`trained_weights/polyworld_backbone`) are missing

### ISSUE THREAD

**Issue by zimka** [zorzi-s/PolyWorldPretrainedNetwork#12]
Hi, thanks for sharing the results of your work.

It looks like there were supposed to be backbone weights (they are [loaded ](https://github.com/zorzi-s/PolyWorldPretrainedNetwork/blob/main/prediction.py#L56) in `prediction.py`)
There is no such file in `trained_weights` however.

If this is not intentional, could you upload the weights?

**Comment by zimka** [comment]
Oops, weights are mentioned in README, my bad.

**Comment by Mingliang-Liu** [comment]
The link to the trained_weights/polyworld_backbone is invalid. Could you send me a copy?
