### ISSUE TITLE
Train on custom datasets

### ISSUE THREAD

**Issue by hehongjie** [zorzi-s/PolyWorldPretrainedNetwork#15]
Thanks for your excellent work and share it here. I have tested it and it worked as expected. I am wondering if you can also share how to train on custom dataset here. Many thanks

**Comment by AlbertoBlackPrint** [comment]
Were you ever able to do it?

**Comment by henokyen** [comment]
I also want to retrain Polyworld with my own dataset. Can you please provide a train.py script that implements your end-to-end training approach?

**Comment by xzw2** [comment]
I also want the train.py. Many thanks

**Comment by lsjBatter** [comment]
Thank you very much for sharing your work. Can you please provide a train.py script？

**Comment by zorzi-s** [comment]
@hehongjie , @AlbertoBlackPrint , @henokyen , @xzw2 , @lsjBatter 

Thank you for the interest on our work! 
As I already mentioned in some closed Issues, making the training code public is not up to me unfortunately. The code is owned by [blackshark.ai](http://blackshark.ai/) and they don’t want to release it fully.

**Comment by hehongjie** [comment]
> Were you ever able to do it?

No. I can't.

**Comment by hehongjie** [comment]
> @hehongjie , @AlbertoBlackPrint , @henokyen , @xzw2 , @lsjBatter
> 
> Thank you for the interest on our work! As I already mentioned in some closed Issues, making the training code public is not up to me unfortunately. The code is owned by [blackshark.ai](http://blackshark.ai/) and they don’t want to release it fully.

Thanks for your reply. Looking forward to your new work.
