### ISSUE TITLE
Question about Differentiable Polygon Rendering

### ISSUE THREAD

**Issue by wanghr-git** [zorzi-s/PolyWorldPretrainedNetwork#18]
@zorzi-s Hello! Very pleased with your work，I don't quite understand the algorithm of one of the modules, the formula of the Differentiable Polygon Rendering algorithm you gave. How det(um,vm) is calculated specifically. Are u, v, m all two-dimensional vectors?

**Comment by zorzi-s** [comment]
Hello @wanghr-git! Yes, u,v, and m are two dimensional vectors. The matrix for the determinant is formed by stacking um and vm next to each other as column vectors.

**Comment by wanghr-git** [comment]
Thank you, I got it! In addition, I would like to ask you another question: in the process of calculating the wraparound number. Do pixel coordinates need to be converted to Cartesian coordinates?

**Comment by zorzi-s** [comment]
@wanghr-git Yes, we normalized pixel coordinates between -1 and 1 (where [-1, -1] is the top left corner of the image).

**Comment by wanghr-git** [comment]
Thank you!
