### ISSUE TITLE
Request for training component

### ISSUE THREAD

**Issue by mohammadreza-sheykhmousa** [zorzi-s/PolyWorldPretrainedNetwork#2]
Het Stefano, glad that you put the code in Github. I appreciate it. However I was wondering if it is possible to train the model from scratch with some custom dataset? Did you also share the training module in the repo? Or I missed it? Thank you @zorzi-s

**Comment by zorzi-s** [comment]
Hi Reza. My apologies, the code is property of blackshark.ai and they prefer not to include the training components in the repo for now.
