### ISSUE TITLE
Problem with choosing backbone

### ISSUE THREAD

**Issue by 654493176** [zorzi-s/PolyWorldPretrainedNetwork#4]
Hi，thank you for your excellent work and code!
I notice you used R2UNet as backbone in your network, compared with the Frame Field Learning  which used UResNet101. And  in this case, your algorithm is more effective. I'd like to know have you tried to use other backbone(like UResNet101 same as FFL) in your network? will them show similar results?
I'll very appreciate for your reply.

**Comment by zorzi-s** [comment]
Hi @654493176,

thank you for the interest on my work!
I didn't deepen into analyzing the performance of different backbones for this task, so I can't really tell for sure which one is better. I can say that I made some early experiments with the UResNet101 (proposed by FFL) and I noticed almost equivalent performance to the residual U-Net.

**Comment by 654493176** [comment]
Thank you for your reply.
I think if your algorithm don't rely on a particular backbone, you should use same backbone in all  network when you compared them(It's easily done, FFL has complete train code). Otherwise,we can't be sure that better results come from different backbone or your excellent  algorithm.
Sorry about my  poor English，I wish you can understand what I mean.I do not doubt your  result,I just think they need a fair Comparison ,Actually in my experiments,R2UNet underperforms UResNet101 on CrowdAI dataset.
Good luck with your research career!

**Comment by zorzi-s** [comment]
@654493176 Thank you for the comment and the suggestion.
I will consider to compare different backbones if an extended version of the paper will be released.

**Comment by 654493176** [comment]
Thank you for your reply and I have no other questions.Looking forward to your further results.
