### ISSUE TITLE
Amazing result! Thanks for your research!

### ISSUE THREAD

**Issue by GSusan** [zorzi-s/PolyWorldPretrainedNetwork#5]
Amazing! Looking forward to your train.py.  Just now, I tried prediction.py with my own dataset, and it's amazing. Though I haven't read the paper, I think your work is so meaningful! Now I have a little confused with offset of the result, I hope that I can solve it after reading the paper. Thanks for your research!
![未命名图片](https://user-images.githubusercontent.com/8318174/170431349-351459c4-e2f0-4e9c-9329-fc4e0ce63799.png)

**Comment by zorzi-s** [comment]
Hi @GSusan , thank you for the interest on our work! :)
