### ISSUE TITLE
Questions about method implementation

### ISSUE THREAD

**Issue by lx709** [zorzi-s/PolyWorldPretrainedNetwork#7]
Hi @zorzi-s, thanks for sharing the code of your interesting work. I have several questions regarding method implementation.
1) When calculating angle loss and mask segmentation loss, the method must determine the instance correspondences between the predicted and GT polygons. How did you determine the instance correspondences?
2) By equations (8) and (9), you are using both clockwise and counterclockwise score matrics. But in your code (lines 156-157 of matching.py), I did not see the difference between these two score matrics. 
3) Would you please provide detailed ablation results for different loss terms?
Thanks for your attention.
Regards,
Xiang

**Comment by zorzi-s** [comment]
Hi @lx709, 

thank you for the interest in our work!

1. Actually it is not necessary to determine the polygon instances. It is sufficient to determine the angle correspondences between predicted and GT polygons. In our case we use the Hungarian algorithm to calculate the permutation matrix given the scores and then we compute the vertex triplets (that define an angle) from it.

2. The lines 156 and 157 initialize the two ScoreNetworks. The score is then computed in the _predict_ method at lines 198-199-200 as described by the equations (8) and (9).

3. The ablation study is available in the supplementary material. 

Best regards,
Stefano

**Comment by GuoxingYan** [comment]
Hello, is the first question clear to you? In my opinion, when you do split loss, you don't need instance matching, but when you do angle loss, you need point-by-point matching.
