### ISSUE TITLE
Challenging Test Set Image IDs for comparison

### ISSUE THREAD

**Issue by yeshwanth95** [zorzi-s/PolyWorldPretrainedNetwork#8]
Hello! Thank you for releasing the code of the model. I find your work really interesting and have been meaning to draw some comparisons on some of the results you report in your paper. In figure 10 of your paper, you illustrate the predictions on some challenging test set images to show how well your model handles them.

Could you kindly share the image IDs of these images so that I can run inference on them and compare them against some of my own experiments? Not exactly a technical issue, but would appreciate it if you could help with this.

Thank you!

**Comment by zorzi-s** [comment]
Hi @yeshwanth95 ,

thank you for the interest, and my apologies for the late reply. 

The image IDs in figure 10 are:

44541    |    21072    |     6519
36517    |    23940    |    23791
7249      |    43110    |    22837
 
Best regards,
Stefano

**Comment by yeshwanth95** [comment]
Hello @zorzi-s , thanks for your reply. Really appreciate it. Will run inferences on these image ids from the crowdAI dataset.
