### ISSUE TITLE
Possibility about doing predictions without ground truth annotation files.

### ISSUE THREAD

**Issue by BradWangW** [zorzi-s/PolyWorldPretrainedNetwork#9]
Hi @zorzi-s, much appreciated for sharing your interesting and knowledgeable work! I am trying to evaluate the model with my own dataset. I have input the pictures as well as the annotation files in MS-COCO format to the model and achieved some meaningful results, but when trying to make predictions simply based on the pictures, I feel a bit perplexed about what type of inputs I am supposed to feed into the model. I tried PIL images and NumPy arrays but failed to execute the prediction step. Could you please give a suggestion on that?

**Comment by zorzi-s** [comment]
Hi @BradWangW ,

the model requires pytorch tensors having dimension [batches, channels, height, width] and the values must be normalized between 0 and 1.
